services:
  nginx:
    build: ./nginx  # Указываем папку с Dockerfile для Nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend  # Указываем папку с Dockerfile для FastAPI
    expose:
      - "8000"